title: CJipy
description: Cjipy's website.
keywords: cjipy, fashion
baseurl: /
url: https://cjipy.github.io/cjipy
# url: http://127.0.0.1:4000
img_path: /assets/img  

author:  
  name: Cjipy  
  logo: assets/img/cjipyLogo.png
  email: blancatjm@gmail.com  # Leave blank if you don't have now

buying:
  email: pjimenezmillas@gmail.com 
# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
#   id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## carousels
index_carousel: off  # index page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rougec
